alias ..="cd .."
alias la="ls -a"
alias dot-edit="nvim $HOME/.dotfiles"
alias dot-link="source $HOME/.dotfiles/link.sh"
alias dot-status="git status $HOME/.dotfiles"
alias dot-add="git add $HOME/.dotfiles"
alias dot-commit="git commit $HOME/.dotfiles"
alias dot-push="git push $HOME/.dotfiles"